export interface ActionData {
  id: number;
  designationEmetteur: string;
  codeIsin: string;
  mnemo: string;
  nomCourt: string;
  cours: string;
  coursPrecedent: string;
  dateCours: string;
  volumeDemande: string;
  volumeOffert: string;
  volumeTransige: string;
  valeurTransige: string;
  nombreTransactions: string;
  statut: string;
  ouverture: string;
  cloture: string;
  seuilHaut: string;
  seuilBas: string;
  variationPourcentage: string;
  coursReferenceSeanceSuivante: string;
  coursDepuisJanvierHaut: string;
  coursDepuisJanvierBas: string;
  variationAnneePrecedente: string;
  extractionId: number;
}

export interface ObligationData {
  id: number;
  designationEmetteur: string;
  designationTitre: string;
  codeIsin: string;
  mnemo: string;
  dateCours: string;
  coursPrecedentEnPourcent: string;
  coursEnFcfa: string;
  nominal: string;
  couponCouru: string;
  volumeDemande: string;
  volumeOffert: string;
  volumeTransige: string;
  nombreTransactions: string;
  statut: string;
  ouverture: string;
  cloture: string;
  seuilHaut: string;
  seuilBas: string;
  variationPourcentage: string;
  coursReferenceSeanceSuivante: string;
  tauxFacial: number | null;
  date1EreCotation: Date | null;
  montantLeve: number | null;
  nombreTitresCotes: number | null;
  maturite: Date | null;
  amortissement: Date | null;
  periodicite: string | null;
  datePrecedenteEcheance: Date | null;
  dateTheoriqueEcheanceSuivante: Date | null;
  encoursCalculeCeJour: number | null;
  rendementNet: number | null;
  rendementBrut: number | null;
  tauxRotationLiquidite: number | null;
  createdAt: Date | null;
  updatedAt: Date | null;
  extractionId: number | null;
  typeObligation: string | null;
  categorie: string | null;
  valeurTransige: number | null;
}
